# Visit https://eksctl.io/ for more info
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test
  region: us-east-1

availabilityZones: ["us-east-1a", "us-east-1b", "us-east-1c", "us-east-1d"]

nodeGroups:
  - name: ng-1
    instanceType: t2.large
    desiredCapacity: 1
    iam:
      withAddonPolicies:
        ebs: true
        fsx: true
        efs: true
  - name: ng-2
    instanceType: t2.large
    desiredCapacity: 1
    iam:
      withAddonPolicies:
        ebs: true
        fsx: true
        efs: true
